### PR TITLE
Use our service to encrypt instead of Cryptobox

### PR DESCRIPTION
**Pull request by danielpassos**
See: [AGDROID-487](https://issues.jboss.org/browse/AGDROID-487)

### CODE REVIEW

**Comment by danielpassos** [comment]
@secondsun @abstractj Could you give it a spin?

**Comment by danielpassos** [comment]
I've decided move it to [aerogear-android-store/](http://github.com/aerogear/aerogear-android-store/), i think it make more sense

**Comment by secondsun** [comment]
CryptoUtil makes a lot more sense in store as well.  +1 to merge

**Comment by abstractj** [comment]
@danielpassos landed here https://github.com/aerogear/aerogear-android-security/commit/2e5405d0bb0c8b838d3c7a4af66cffb8856ba73e

**Pull request closed without merging**
